name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: nest-challenge

      cache:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          
      - run: npm ci
      
      - run: echo "Decoded JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY | base64 -d }}"
      - run: echo "Decoded JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY | base64 -d }}"
      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/nest-challenge?schema=public"
          AWS_BUCKET_NAME: "ignite-nest-clean"
          CLOUDFLARE_ACCOUNT_ID: "584075bcc0c6c67478761fe805d67a79"
          AWS_ACCESS_KEY_ID: "c3c2b62831a0479fcfc453f02c04d142"
          AWS_SECRET_ACCESS_KEY: "9d926492911c6a58816bf1fb8796c0485020c94637c69d4edacff75095fe3af8"
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        
